language: go
go:
        - tip

install:
        - go get github.com/mattn/goveralls
        - go build github.com/mattn/goveralls
script:
        - go test -covermode=atomic -coverprofile=profile.cov 
        - ls $HOME/gopath
        - $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci
 
